spring.application.name=brewery-management-api

# Configuración de H2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:brewerydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=fran
spring.datasource.password=

# Mostrar las consultas SQL en la consola para aprender qué hace Hibernate
spring.jpa.show-sql=true
# warnings de que Spring mantiene abierta la sesión de Hibernate durante toda la request. desactivado
spring.jpa.open-in-view=false