spring.application.name=brewery-management-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/brewery_db
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true